export const MAX_LINKS_PER_CHANNEL = 5;

export const CAST_COMMAND_NAME = 'cast';
export const CAST_COMMAND_TELEGRAM_KEY_OPTION = 'telegramkey';
export const CAST_COMMAND_CHANNEL_OPTION = 'channel';

export const MANAGE_COMMAND_NAME = 'manage';
export const MANAGE_COMMAND_CHANNEL_OPTION = 'channel';
export const MANAGE_COMMAND_SELECT_CONNECTION_ID = 'select_connection';

export const MANAGE_COMMAND_HIDE_BUTTON_ID = 'hide';
export const MANAGE_COMMAND_UPDATE_BUTTON_ID = 'update';
export const MANAGE_COMMAND_DELETE_BUTTON_ID = 'delete';
export const MANAGE_COMMAND_SOURCE_BUTTON_ID = 'source';
export const MANAGE_COMMAND_CHANNEL_HASHTAG_BUTTON_ID = 'channel_hashtag';
export const MANAGE_COMMAND_CREDITS_BUTTON_ID = 'credits';
export const ALL_MANAGE_COMMAND_BUTTON_IDS = [
  MANAGE_COMMAND_HIDE_BUTTON_ID,
  MANAGE_COMMAND_UPDATE_BUTTON_ID,
  MANAGE_COMMAND_DELETE_BUTTON_ID,
  MANAGE_COMMAND_SOURCE_BUTTON_ID,
  MANAGE_COMMAND_CHANNEL_HASHTAG_BUTTON_ID,
  MANAGE_COMMAND_CREDITS_BUTTON_ID,
];
